# Generated by Django 6.0 on 2025-12-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StationLine',
        ),
    ]
