# Generated by Django 6.0 on 2025-12-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('cut_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True, null=True)),
                ('cut_order', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cuts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('episode_num', models.IntegerField()),
                ('subtitle', models.CharField(max_length=255)),
                ('history_summary', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'episodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoriesEpisode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('episode_num', models.IntegerField()),
                ('subtitle', models.CharField(max_length=255)),
                ('history_summary', models.TextField()),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stories_episode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('webtoon_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='webtoons/thumbnails/')),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webtoons',
                'managed': False,
            },
        ),
    ]
