# Generated by Django 6.0 on 2026-03-06 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='storiesepisode',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='webtoon',
            options={'managed': True},
        ),
    ]
